import Head from "next/head";
import { Fragment } from "react";
import Link from "next/link";

const Layout = ({ children }) => {
  return (
    <Fragment>
      <Head>
        <title>Tablas Dinamicas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        ></meta>
      </Head>

      <header>
        <span>Tabla Dinamica</span>
      </header>

      <nav className="nav">
        <Link href="/">
          <span>Albums</span>
        </Link>
        <Link href="/users">
          <span>Users</span>
        </Link>
        <Link href="/todos">
          <span>Todos</span>
        </Link>
      </nav>

      <main className="main">{children}</main>

      <footer className="footer">footer</footer>
    </Fragment>
  );
};

export default Layout;
