import Head from 'next/head';
import Link from 'next/link';

const Layout = ({ children }) => {
    return (
        <div className="container">
            <Head>
                <title>Tablas Dinamicas</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header>
                <span>Tabla Dinamica</span>
            </header>
            
            <nav className="nav">
                <Link href="/"><span>Albums</span></Link>
                <Link href="/users"><span>Users</span></Link>
                <Link href="/todos"><span>Todos</span></Link>
            </nav>

            <main className="main">
                {children}
            </main>

            <footer className="footer">
                footer
            </footer>
        </div>
    )
}

export default Layout
